version: "3.7"

services:

  app_proxy:
    environment:
      APP_HOST: retro-mike-btc-node_web_1
      APP_PORT: 8080
  web:
    image: amir20/dozzle:v8.12.8@sha256:8ff3115c9c9dd7576839df6f2575de345ca7cafa398cf2496f1f19c31d862ac1
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    restart: on-failure
    depends_on:
      - node
  node:
    image: theretromike/nodes:bitcoin
    restart: on-failure
    stop_grace_period: 1m
    volumes:
      - ${APP_DATA_DIR}/.bitcoin:/root/.bitcoin
    ports:
      - 9004:9004    # RPC
      - 7004:7004    # ZMQ
      - 8333:8333    # P2P
    entrypoint: "bitcoind -printtoconsole -server -prune=550 -wallet=default -zmqpubhashblock=tcp://127.0.0.1:7004 -rpcbind=0.0.0.0 -rpcport=9004 -rpcallowip=0.0.0.0/0 -port=8333 -rpcuser=pooluser -rpcpassword=poolpassword"
