version: "3.7"

services:

  app_proxy:
    environment:
      APP_HOST: retro-mike-bsv-node_web_1
      APP_PORT: 8080
  web:
    image: amir20/dozzle:v8.12.8@sha256:8ff3115c9c9dd7576839df6f2575de345ca7cafa398cf2496f1f19c31d862ac1
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    restart: on-failure
    depends_on:
      - node
  node:
    image: theretromike/nodes:bitcoinsv
    restart: on-failure
    stop_grace_period: 1m
    volumes:
      - ${APP_DATA_DIR}/.bitcoinsv:/root/.bitcoin
    ports:
      - 9005:9005    # RPC
      - 7005:7005    # ZMQ
      - 8335:8335    # P2P
    entrypoint: "bitcoind -printtoconsole -server -prune=550 -wallet=default -zmqpubhashblock=tcp://127.0.0.1:7005 -rpcbind=0.0.0.0 -rpcport=9005 -rpcallowip=0.0.0.0/0 -port=8335 -rpcuser=pooluser -rpcpassword=poolpassword -maxmempool=10000 -maxsigcachesize=250 -maxscriptcachesize=250 -maxorphantx=10000 -maxstackmemoryusageconsensus=1000000000 -excessiveblocksize=10000000000 -minminingtxfee=0.00000500"
