version: "3.7"

services:

  app_proxy:
    environment:
      APP_HOST: retro-mike-dgb-node-sha256_web_1
      APP_PORT: 8080
  web:
    image: amir20/dozzle:v8.12.8@sha256:8ff3115c9c9dd7576839df6f2575de345ca7cafa398cf2496f1f19c31d862ac1
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    restart: on-failure
    depends_on:
      - digibyted
  digibyted:
    image: theretromike/nodes:digibyte
    restart: on-failure
    stop_grace_period: 1m
    volumes:
      - ${APP_DATA_DIR}/.digibyte:/root/.digibyte
    ports:
      - 9001:9001    # RPC
      - 7001:7001    # ZMQ
      - 12024:12024  # P2P
    entrypoint: "digibyted -printtoconsole -server -algo=sha256d -prune=550 -wallet=default -zmqpubhashblock=tcp://127.0.0.1:7001 -rpcbind=0.0.0.0 -rpcport=9001 -rpcallowip=0.0.0.0/0 -rpcauth=pooluser:bc1f961ad347f79ab97fa7e3ac35f02a$$eb31de681359ba83be70e2cc178bf7de7b3b7affb29df2fb41907436d8ef734e"
